Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,37 +22,9 @@ jobs:
       id: printToken
       run: echo "${{ github.token }}"
     
-    # - name: IQ Evaluate
-    #   id: evaluate
-    #   uses: sonatype/actions/evaluate@v1.0.6-beta
-    #   with:
-    #     username: ${{ secrets.SSA_USERNAME }}
-    #     password: ${{ secrets.SSA_PASSWORD }}
-    #     iq-server-url: https://sonatype.sonatype.app/platform
-    #     application-id: testdata
-    #     result-file: result
-    #     keep-scan-file: true
-    #     scan-targets: pom.xml
-    #     debug: false
-    #     ignore-system-errors: true
-    #     ignore-scanning-errors: true
-    #     # sarif-file: myfile.sarif
-    #     upload-sarif-file: true
-
-    - name: Setup IQ CLI Action
-      id: setup-iq-cli
-      uses: sonatype/actions/setup-iq-cli@v1.0.6-beta
-      with:
-        iq-cli-version: 'latest'
-
-    - uses: actions/setup-java@v4
-      with:
-        distribution: 'temurin'
-        java-version: '17'
-
-    - name: Run IQ CLI Action
-      id: run-iq-cli
-      uses: sonatype/actions/run-iq-cli@v1.0.6-beta
+    - name: IQ Evaluate
+      id: evaluate
+      uses: sonatype/actions/evaluate@v1.0.6-beta
       with:
         username: ${{ secrets.SSA_USERNAME }}
         password: ${{ secrets.SSA_PASSWORD }}
@@ -64,22 +36,50 @@ jobs:
         debug: false
         ignore-system-errors: true
         ignore-scanning-errors: true
-        sarif-file: myfile.sarif
+        # sarif-file: myfile.sarif
+        upload-sarif-file: true
 
-    - name: showing outputs
-      if: ( success() || failure() )
-      run: |
-        echo ${{ steps.run-iq-cli.outputs.sarif-file }}
-        echo ${{ steps.run-iq-cli.outputs.sarif-file != '' }} 
-        cat ${{ steps.run-iq-cli.outputs.sarif-file }}
+    # - name: Setup IQ CLI Action
+    #   id: setup-iq-cli
+    #   uses: sonatype/actions/setup-iq-cli@v1.0.6-beta
+    #   with:
+    #     iq-cli-version: 'latest'
+
+    # - uses: actions/setup-java@v4
+    #   with:
+    #     distribution: 'temurin'
+    #     java-version: '17'
+
+    # - name: Run IQ CLI Action
+    #   id: run-iq-cli
+    #   uses: sonatype/actions/run-iq-cli@v1.0.6-beta
+    #   with:
+    #     username: ${{ secrets.SSA_USERNAME }}
+    #     password: ${{ secrets.SSA_PASSWORD }}
+    #     iq-server-url: https://sonatype.sonatype.app/platform
+    #     application-id: testdata
+    #     result-file: result
+    #     keep-scan-file: true
+    #     scan-targets: pom.xml
+    #     debug: false
+    #     ignore-system-errors: true
+    #     ignore-scanning-errors: true
+    #     sarif-file: myfile.sarif
+
+    # - name: showing outputs
+    #   if: ( success() || failure() )
+    #   run: |
+    #     echo ${{ steps.run-iq-cli.outputs.sarif-file }}
+    #     echo ${{ steps.run-iq-cli.outputs.sarif-file != '' }} 
+    #     cat ${{ steps.run-iq-cli.outputs.sarif-file }}
         
-    - name: showing resulting file
-      if: steps.run-iq-cli.outputs.sarif-file && ( success() || failure() )
-      run: |
-        echo ${{ steps.run-iq-cli.outputs.sarif-file }}
-        echo ${{ steps.run-iq-cli.outputs.sarif-file != '' }} 
-        cat ${{ steps.run-iq-cli.outputs.sarif-file }}
-        ls -la 
+    # - name: showing resulting file
+    #   if: steps.run-iq-cli.outputs.sarif-file && ( success() || failure() )
+    #   run: |
+    #     echo ${{ steps.run-iq-cli.outputs.sarif-file }}
+    #     echo ${{ steps.run-iq-cli.outputs.sarif-file != '' }} 
+    #     cat ${{ steps.run-iq-cli.outputs.sarif-file }}
+    #     ls -la 
     
     # - name: Fetch SBOM
     #   uses: sonatype/actions/fetch-sbom@v1
